auto_aim:
  detector:
    model_path: "/home/ziyu/ziyu/codes/ne_vision/install/share/model/0708"
  tracker_2d:
    # tracker_2d 卡尔曼参数
    sigma_q_x: 1000.0
    sigma_q_y: 1000.0
    sigma_r_x: 0.1
    sigma_r_y: 0.1
